### ISSUE TITLE
TODO: system ogłoszeń o kupnie na chacie

### ISSUE THREAD

**Issue by Kamilkime** [ivall/VIshop-plugin#10]

**Comment by deestt** [comment]
wraz z hex kolorami (&#ffffff)

**Comment by Tems-py** [comment]
w zasadzie to trzeba poprawić #2

**Comment by maxcom1** [comment]
W sumie wszystkie/większość poprawek wprowadziłem jakiś czas temu, ale trzeba będzie dostosować wszystko pod obecną formę wsparcia kilku platform

**Comment by Kamilkime** [comment]
System ogłoszeń jednak niepotrzebnie będzie komplikował plugin (szczególnie teraz, jak dodane jest kilka platform). Zamiast tego zalecane będzie użycie [/tellraw](https://minecraft.fandom.com/wiki/Commands/tellraw), jest trochę różnych generatorów w necie (np. [ten](https://www.minecraftjson.com/))

**Comment by deestt** [comment]
można zrobić w abstractcie

**Comment by Kamilkime** [comment]
> można zrobić w abstractcie

Eee... Że co?

**Comment by deestt** [comment]
> > można zrobić w abstractcie
> 
> Eee... Że co?

no tak jak zrobiles w commonsach w tasku

**Comment by Kamilkime** [comment]
> no tak jak zrobiles w commonsach w tasku

Ale dla platform innych niż Bukkit - implementacja byłaby upierdliwa. No i jednak jest to nadal zbędne - `/tellraw` może robić dokładnie to samo, a jednocześnie ma znacznie większe możliwości (title, pełne formatowanie wiadomości, wybór odbiorców, itd.), których nigdy byśmy nie dodali do takich ogłoszeń
