### ISSUE TITLE
Użycie GSON#toJson

### ISSUE THREAD

**Issue by deestt** [ivall/VIshop-plugin#11]
Czy Jacksona tak jak GOXY. zmniejszy to trochę kodu

**Comment by Kamilkime** [comment]
Ale po co nam toJson(), jak nigdzie nie robimy JSONa z żadnych obiektów

**Comment by Kamilkime** [comment]
Chyba że chodziło ci o coś takiego: https://github.com/ivall/VIshop-plugin/blob/2.0/common/src/main/java/pl/vishop/plugin/request/PendingOrderRequest.java#L60

**Comment by deestt** [comment]
a
