### ISSUE TITLE
Błąd w bukkitcie

### ISSUE THREAD

**Issue by deestt** [ivall/VIshop-plugin#13]
Wiem że w bukkitcie nie mozna uzyc dispathCommand w asyncu więc trzeba usunąc async

**Comment by deestt** [comment]
#14

**Comment by deestt** [comment]
nie wiem jak jest w bungee ale pewnie tak samo jak bukkit

**Comment by Kamilkime** [comment]
Było testowane - w bungee wszystko działa, a bukkitowe są wykonywane sync:
https://github.com/ivall/VIshop-plugin/blob/main/bukkit/src/main/java/pl/vishop/plugin/bukkit/BukkitOrderTask.java#L50-L53

**Comment by deestt** [comment]
a
